package Models.AnnouncementByID;

public class ReqBaseAnnouncement {
    public int id;
    public String dType;
    public String dateOfAnnouncement;
    public Object cbApproved;
    public boolean cbApprovedReceived;
    public boolean cbApprovedNotRequired;
    public boolean cbApprovedPending;
    public Object remarks;
    public Object approveStatus;
    public Object cseComment;
    public Object createdDate;
    public Object updatedDate;
    public Object approveStatusDisplay;
    public Object company;
    public Object announcementDocuments;
    public Object dateOfInitialAnnouncement;
    public Object otherRemark;
    public boolean votingShare;
    public boolean noneVotingShare;
    public Object divPerShare;
    public double votingDivPerShare;
    public Object nonVotingDivPerShare;
    public boolean typeFirstInt;
    public boolean typeSecondInt;
    public boolean typeThirdInt;
    public boolean typeFourthInt;
    public Object typeFinalInt;
    public boolean firstAndFinal;
    public boolean finalDividend;
    public boolean typeOther;
    public String financialYear;
    public String shrHolderApproval;
    public Object agm;
    public String xd;
    public String payment;
    public String shareTransferBook;
    public Object centralBankApproval;
}
